import 'package:test/test.dart';

import 'package:drais_server/auth/password.dart';
import 'package:drais_server/auth/rbac.dart';
import 'package:drais_server/db/database.dart';

/// Pure-function tests for the Dart auth implementation.
///
/// No database, no network — these cover the logic that would silently
/// diverge from the platform, which is where a rewrite actually goes wrong.
void main() {
  group('Password — cross-implementation compatibility', () {
    // Generated by Node's bcryptjs at rounds 12 — the library that hashed
    // every password currently in the users table. 37 of 38 rows are $2b$.
    //
    // If this test fails, existing users cannot sign in against the Dart
    // server and the migration is dead. It is the single most important
    // assertion in this package.
    const String nodeHash2b =
        r'$2b$12$AGped4t7.IiDcMKAvtQsY.TIINwHO3jFWZ2fq5T/2TJf4L0RpbQVm';
    const String plaintext = 'DraisTest!2026';

    test('verifies a hash produced by Node bcryptjs (\$2b\$)', () {
      expect(Password.verify(plaintext, nodeHash2b), isTrue);
    });

    test('rejects the wrong password against a Node hash', () {
      expect(Password.verify('nope', nodeHash2b), isFalse);
    });

    test('round-trips its own hashes', () {
      final String hash = Password.hash(plaintext);
      expect(Password.verify(plaintext, hash), isTrue);
      expect(Password.verify('different', hash), isFalse);
    });

    test('returns false rather than throwing on malformed input', () {
      // A corrupt row must not become a 500 — that would tell an attacker
      // the account exists.
      expect(Password.verify(plaintext, null), isFalse);
      expect(Password.verify(plaintext, ''), isFalse);
      expect(Password.verify(plaintext, 'not-a-hash'), isFalse);
      expect(Password.verify(plaintext, r'$2b$12$tooshort'), isFalse);
    });

    test('rejects an empty password against a valid hash', () {
      expect(Password.verify('', nodeHash2b), isFalse);
    });
  });

  group('Rbac.expandChain — must match the platform exactly', () {
    test('expands a dotted code outward, then the universal grant', () {
      expect(
        Rbac.expandChain('academics.results.update'),
        <String>[
          'academics.results.update',
          'academics.results.*',
          'academics.*',
          '*',
        ],
      );
    });

    test('a single segment expands to itself plus the universal grant', () {
      expect(Rbac.expandChain('dashboard'), <String>['dashboard', '*']);
    });

    test('an empty code expands to nothing', () {
      expect(Rbac.expandChain(''), isEmpty);
    });
  });

  group('Rbac.allows', () {
    test('grants on an exact match', () {
      expect(
        Rbac.allows(<String>['finance.payments.create'], 'finance.payments.create'),
        isTrue,
      );
    });

    test('grants via a prefix wildcard', () {
      expect(
        Rbac.allows(<String>['finance.*'], 'finance.payments.create'),
        isTrue,
      );
    });

    test('grants everything with the universal grant', () {
      expect(Rbac.allows(<String>['*'], 'anything.at.all'), isTrue);
    });

    test('does not grant a sibling branch', () {
      expect(
        Rbac.allows(<String>['finance.*'], 'academics.results.update'),
        isFalse,
      );
    });

    test('grants nothing when nothing is held', () {
      expect(Rbac.allows(const <String>[], 'dashboard'), isFalse);
    });
  });

  group('SQL placeholder conversion', () {
    test('rewrites positional markers in order', () {
      expect(
        'SELECT * FROM users WHERE email = ? AND school_id = ?'
            .toNamedPlaceholders(),
        'SELECT * FROM users WHERE email = :p0 AND school_id = :p1',
      );
    });

    test('leaves a question mark inside a string literal alone', () {
      // Rewriting this would corrupt the statement.
      expect(
        "SELECT '?' AS q WHERE id = ?".toNamedPlaceholders(),
        "SELECT '?' AS q WHERE id = :p0",
      );
    });

    test('is a no-op when there are no placeholders', () {
      expect('SELECT 1'.toNamedPlaceholders(), 'SELECT 1');
    });
  });

  group('Database.limitClause — the TiDB trap', () {
    test('emits literal integers, never bound parameters', () {
      expect(Database.limitClause(limit: 25), 'LIMIT 25 OFFSET 0');
      expect(
        Database.limitClause(limit: 50, offset: 100),
        'LIMIT 50 OFFSET 100',
      );
    });

    test('clamps out-of-range values', () {
      expect(Database.limitClause(limit: 0), contains('LIMIT 1'));
      expect(Database.limitClause(limit: 99999), contains('LIMIT 500'));
      expect(Database.limitClause(limit: 10, offset: -5), contains('OFFSET 0'));
    });
  });
}
